### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Zordon1337** [Igoorx/osuBancho#7]
![2](https://user-images.githubusercontent.com/65111609/152650709-0f3f8cd3-c1b1-4883-ad71-04c356d3cd50.png)
![3](https://user-images.githubusercontent.com/65111609/152650710-bf1bf0db-2fa3-4221-823e-213463cefa67.png)
![1](https://user-images.githubusercontent.com/65111609/152650711-24dea570-6e7d-408b-825f-f2bde05c46d0.png)

**Comment by lokillo-0** [comment]
that error could never be resolved, I recommend that you use [gulag](https://github.com/cmyui/gulag) or ripple, this will not work with current versions of osu and if you download an old version it is likely that the maps will come out with errors and the game will not allow you to play them

**Comment by Igoorx** [comment]
Thanks for your interest in this project.
This isn't possible because this server doesn't handle scores, the scores would need to be handled in a separate web server, also, this is an old outdated server emulator, so you should do as @lokillo999 said and use a newer and maintained server.

I will actually use this opportunity to archive this project, I didn't do this before because I was planning to implement the scores handling in the server but I never got to do this and I don't feel like I will ever do it lol
